Improve performance, fix bug with standard EDEK parsing
IronCoreLabs/ironcore-alloy pull request #114
Opened 2024-04-26 19:12 UTC by giarc3

Lots of changes:
- Adds rayon, uses `into_par_iter()` to add parallelism to per-field and per-document computations
- Fix bug with standard EDEK parsing where V4 header variants weren't being created
- Some changes to Cargo.toml for binary size improvements
- Add additional check to standard decrypt, making sure that KeyIdHeader KeyId matches an Edek from V4DocumentHeader
- Fix several tests around document headers

Note that CI won't pass until the ironcore-documents PR merges

2024-04-26 19:30 UTC, BobWall23 approved these changes

2024-04-29 21:40 UTC, coltfred requested changes
Build is broken from uniffi changes and a rogue debug. Other than that, it LGTM!

2024-04-29 21:40 UTC, coltfred commented on src/saas_shield/standard.rs
> +        dbg!(&kms_config_ids);
```suggestion
```

2024-04-29 21:40 UTC, coltfred commented on Cargo.toml
> +uniffi = { git = "https://github.com/mozilla/uniffi-rs", features = ["cli"] }
Build seems to indicate that this change doesn't work. https://github.com/IronCoreLabs/ironcore-alloy/actions/runs/8884446697/job/24393687125?pr=114#step:7:222

2024-05-02 15:31 UTC, coltfred approved these changes

2024-05-02 20:05 UTC, merged